"""Data models for the feedback system."""

from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from typing import Any, Dict, List, Optional


class QueryCategory(str, Enum):
    """Categories for generated queries."""

    SIMPLE_PERIOD = "simple_period"
    NAMED_QUARTER = "named_quarter"
    DYNAMIC_LAST_N = "dynamic_last_n"
    BUSINESS_DAYS = "business_days"
    YTD = "ytd"
    CUSTOM_RANGE = "custom_range"
    COMPARISON = "comparison"
    DOW_FILTER = "dow_filter"
    WEEKEND = "weekend"
    NAMED_MONTH = "named_month"
    NAMED_YEAR = "named_year"
    EVENT_QUERY = "event_query"
    EDGE_CASE = "edge_case"
    LOOKBACK_BOUNDARY = "lookback_boundary"
    INVALID_QUERY = "invalid_query"
    COMPOSITIONAL = "compositional"


class ValidationResult(str, Enum):
    """Result of validating a single query."""

    PASS = "pass"
    FAIL_START_DATE = "fail_start_date"
    FAIL_END_DATE = "fail_end_date"
    FAIL_CALENDAR_DAYS = "fail_calendar_days"
    FAIL_PERIOD_TYPE = "fail_period_type"
    FAIL_SUCCESS_FLAG = "fail_success_flag"
    FAIL_INTENT_TYPE = "fail_intent_type"
    FAIL_EXCEPTION = "fail_exception"


@dataclass
class ChallengerQuery:
    """A query generated by the Challenger Agent with ground truth."""

    query_id: str
    query_text: str
    language: str  # "es" or "en"
    category: QueryCategory
    reference_date: date

    # Expected ground truth
    expected_success: bool
    expected_start_date: Optional[str] = None  # YYYY-MM-DD
    expected_end_date: Optional[str] = None
    expected_calendar_days: Optional[int] = None
    expected_period_type: Optional[str] = None
    expected_intent_type: Optional[str] = None  # "resolve_period", "event_lookup", etc.

    # Metadata
    difficulty: str = "medium"
    description: str = ""


@dataclass
class ValidationReport:
    """Result of validating one query."""

    query: ChallengerQuery
    agent_output: Dict[str, Any]
    result: ValidationResult
    mismatches: Dict[str, Dict[str, Any]]
    error_traceback: Optional[str] = None
    duration_ms: float = 0.0


@dataclass
class FixAttempt:
    """Record of an auto-fix attempt."""

    attempt_number: int
    file_path: str
    original_code: str
    proposed_fix: str
    fix_description: str
    fix_applied: bool
    fix_verified: bool
    regression_test_passed: bool
    error_message: Optional[str] = None


@dataclass
class QueryResult:
    """Complete result for a single query in the feedback loop."""

    query: ChallengerQuery
    validation: ValidationReport
    fix_attempts: List[FixAttempt] = field(default_factory=list)
    final_status: str = "pending"  # "passed", "fixed", "skipped"
